version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        // Enable WP_DEBUG mode
        define( 'WP_DEBUG', true );
        // Enable Debug logging to the /wp-content/debug.log file
        define( 'WP_DEBUG_LOG', true );
        // Disable display of errors and warnings
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
    volumes:
      - wordpress:/var/www/html
      - ./bootscore:/var/www/html/wp-content/themes/bootscore
      - ./theme:/var/www/html/wp-content/themes/kp-theme

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
