name: Deploy to staging

on:
  push:
    branches:
      - "main"
    paths:
      - "theme/**"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to staging
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET: ${{ secrets.STAGING_TARGET }}
          VERBOSE: true
          USER: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          SOURCE: ./theme/
          ARGS: -az --exclude=/.git/
          
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"