name: Deploy to staging

on:
  push:
    branches:
      - "main"
    paths:
      - "theme/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to staging
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: theme/
          legacy_allow_rsa_hostkeys: "true"
          remote_path: ${{ secrets.STAGING_TARGET }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}