name: Deploy to staging

on:
  push:
    branches:
      - "main"
    paths:
      - "theme/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to staging
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET: ${{ secrets.STAGING_TARGET }}
          USER: ${{ secrets.SSH_USER }}
          SOURCE: ./theme/
          ARGS: -az --exclude=/.git/
          SSH_ARGS: -p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"